---
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

processors:
  batch:

exporters:
  logging:
    loglevel: "debug"
  otlp:
    endpoint: "tempo:4317"
    compression: "none"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: ["otlp"]
      processors: ["batch"]
      exporters: ["otlp"]
  telemetry:
    logs:
      level: "info"
    metrics:
      address: ":8888"
