---
name: "Lint"
on:  # yamllint disable-line rule:truthy
  - "push"
  - "pull_request"
jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "authzed/actions/yaml-lint@main"
      - uses: "instrumenta/kubeval-action@5915e4adba5adccac07cb156b82e54c3fed74921"
        with:
          files: "kubernetes"

