---
name: "Test"
on:  # yamllint disable-line rule:truthy
  push:
    paths: ["integration-testing/**"]
  pull_request:
    paths: ["integration-testing/**"]
jobs:
  integration-testing:
    name: "Run Integration Test Example"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-go@v3"
        with:
          go-version: "~1.19.1"
      - uses: "authzed/actions/go-test@main"
        with:
          working_directory: "integration-testing"
